server:
  port: 9000

spring:
  application:
    name: mesh
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/3dtask?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update